steps:

# # Installing dependencies
# - id: installing python
#   name: python
#   entrypoint: pip
#   args: ['install', '-r', 'requirements.txt', "--user"]

# Building the container image
- id: docker build
  name: 'gcr.io/cloud-builders/docker'
  dir: "/Users/nombauser/Desktop/GIT/my_git_repos/mongo_to_bq/CLOUD_RUN"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/watch-changestream-for-pubsub', '.']

# Push the container image to Container Registry
- id: docker push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/watch-changestream-for-pubsub']

# Deploy container image to Cloud Run
- id: Deploy to Cloud Run
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  dir: "/Users/nombauser/Desktop/GIT/my_git_repos/mongo_to_bq/CLOUD_RUN"
  secretEnv:
    - MONGODB_URI
    - MONGO_CLUSTER
    - MONGO_DATA_BASE
    - PROJECT_ID
    - TOPIC_ID1
  args:
  - "-c"
  - gcloud run deploy watch-changestream-for-pubsub \
    --image gcr.io/$PROJECT_ID/watch-changestream-for-pubsub \
    --region europe-west1 \
    --platform managed \
    --allow-unauthenticated \
    --min-instances 1 \
    --max-instances 1 \
    --set-env-vars "MONGODB_URI=$$MONGODB_URI
    --set-env-vars "MONGO_CLUSTER=$$MONGO_CLUSTER
    --set-env-vars "MONGO_DATA_BASE=$$MONGO_DATA_BASE
    --set-env-vars "PROJECT_ID=$$PROJECT_ID
    --set-env-vars "TOPIC_ID1=$$TOPIC_ID1

availableSecrets:
  secretManager:
  - versionName: proprojects/34188081344/secrets/MONGODB_URI/versions/latest
    env: 'MONGODB_URI'
  - versionName: proprojects/34188081344/secrets/MONGO_CLUSTER/versions/latest
    env: 'MONGO_CLUSTER'
  - versionName: proprojects/34188081344/secrets/MONGO_DATA_BASE/versions/latest
    env: 'MONGO_DATA_BASE'
  - versionName: proprojects/34188081344/secrets/PROJECT_ID/versions/latest
    env: 'PROJECT_ID'
  - versionName: proprojects/34188081344/secrets/TOPIC_ID1/versions/latest
    env: 'TOPIC_ID1'

images:
- gcr.io/$PROJECT_ID/watch-changestream-for-pubsub

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s